### ISSUE TITLE
Nodejs4.3 No Longer Supported by Lambda

### ISSUE THREAD

**Issue by scottdix** [aws-quickstart/quickstart-compliance-common#20]
When Config Rules are set to True, the following error occurs:

CREATE_FAILED | The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException

**Comment by andrew-glenn** [comment]
Migrated to Python 3.x
